version: 2
updates:
  # Monitor npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    # Bundle updates into one PR
    groups:
      all:
        applies-to: version-updates
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
  # Monitor Python dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    # Bundle updates into one PR
    groups:
      all:
        applies-to: version-updates
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
  # Monitor GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Bundle updates into one PR
    groups:
      all:
        applies-to: version-updates
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
